# Generated by Django 2.0.5 on 2018-05-21 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_auto_20180518_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='project_position',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teams.ProjectPosition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='new', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectposition',
            name='applicants',
            field=models.ManyToManyField(through='teams.Application', to=settings.AUTH_USER_MODEL),
        ),
    ]
