# Generated by Django 2.0.5 on 2018-05-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20180521_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectposition',
            name='status',
            field=models.CharField(default='open', max_length=25),
            preserve_default=False,
        ),
    ]
