# Generated by Django 2.0.5 on 2018-05-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20180523_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectposition',
            name='duration',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
