# Generated by Django 2.0.5 on 2018-05-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_projectposition_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='positions',
            field=models.ManyToManyField(to='teams.Position'),
        ),
    ]
