# Generated by Django 2.0.5 on 2018-05-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_userprofile_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherproject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='otherproject',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='other_projects', to='teams.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='teams.UserProfile'),
            preserve_default=False,
        ),
    ]
