# Generated by Django 2.0.5 on 2018-05-30 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20180530_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherproject',
            old_name='user_profile',
            new_name='user',
        ),
    ]
